# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygraph_Opencv.ui'
#
# Created: Mon Oct 06 20:40:54 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_Qt_CV_MainWindow(object):
	def setupUi(self, Qt_CV_MainWindow):
		Qt_CV_MainWindow.setObjectName(_fromUtf8("Qt_CV_MainWindow"))
		Qt_CV_MainWindow.resize(623, 684)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(Qt_CV_MainWindow.sizePolicy().hasHeightForWidth())
		Qt_CV_MainWindow.setSizePolicy(sizePolicy)
		Qt_CV_MainWindow.setMouseTracking(True)
		Qt_CV_MainWindow.setAcceptDrops(False)
		self.centralwidget = QtGui.QWidget(Qt_CV_MainWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.layoutWidget = QtGui.QWidget(self.centralwidget)
		self.layoutWidget.setGeometry(QtCore.QRect(10, 140, 591, 41))
		self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
		self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.file_edit = QtGui.QLineEdit(self.layoutWidget)
		self.file_edit.setObjectName(_fromUtf8("file_edit"))
		self.horizontalLayout.addWidget(self.file_edit)
		self.file_button = QtGui.QPushButton(self.layoutWidget)
		self.file_button.setObjectName(_fromUtf8("file_button"))
		self.horizontalLayout.addWidget(self.file_button)
		self.pic_view = GraphicsLayoutWidget(self.centralwidget)
		self.pic_view.setGeometry(QtCore.QRect(10, 190, 591, 431))
		self.pic_view.setViewportUpdateMode(QtGui.QGraphicsView.FullViewportUpdate)
		self.pic_view.setObjectName(_fromUtf8("pic_view"))
		self.edge_con_ckbox = QtGui.QCheckBox(self.centralwidget)
		self.edge_con_ckbox.setGeometry(QtCore.QRect(460, 100, 121, 16))
		self.edge_con_ckbox.setObjectName(_fromUtf8("edge_con_ckbox"))
		self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
		self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 411, 114))
		self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
		self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
		self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
		self.verticalLayout = QtGui.QVBoxLayout()
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.label = QtGui.QLabel(self.layoutWidget1)
		self.label.setObjectName(_fromUtf8("label"))
		self.verticalLayout.addWidget(self.label)
		self.label_2 = QtGui.QLabel(self.layoutWidget1)
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.verticalLayout.addWidget(self.label_2)
		self.label_3 = QtGui.QLabel(self.layoutWidget1)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.verticalLayout.addWidget(self.label_3)
		self.label_4 = QtGui.QLabel(self.layoutWidget1)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.verticalLayout.addWidget(self.label_4)
		self.horizontalLayout_2.addLayout(self.verticalLayout)
		self.verticalLayout_3 = QtGui.QVBoxLayout()
		self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
		self.threshold1_lcd = QtGui.QLCDNumber(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.threshold1_lcd.sizePolicy().hasHeightForWidth())
		self.threshold1_lcd.setSizePolicy(sizePolicy)
		self.threshold1_lcd.setObjectName(_fromUtf8("threshold1_lcd"))
		self.verticalLayout_3.addWidget(self.threshold1_lcd)
		self.threshold2_lcd = QtGui.QLCDNumber(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.threshold2_lcd.sizePolicy().hasHeightForWidth())
		self.threshold2_lcd.setSizePolicy(sizePolicy)
		self.threshold2_lcd.setObjectName(_fromUtf8("threshold2_lcd"))
		self.verticalLayout_3.addWidget(self.threshold2_lcd)
		self.max_area_lcd = QtGui.QLCDNumber(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.max_area_lcd.sizePolicy().hasHeightForWidth())
		self.max_area_lcd.setSizePolicy(sizePolicy)
		self.max_area_lcd.setObjectName(_fromUtf8("max_area_lcd"))
		self.verticalLayout_3.addWidget(self.max_area_lcd)
		self.min_area_lcd = QtGui.QLCDNumber(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.min_area_lcd.sizePolicy().hasHeightForWidth())
		self.min_area_lcd.setSizePolicy(sizePolicy)
		self.min_area_lcd.setObjectName(_fromUtf8("min_area_lcd"))
		self.verticalLayout_3.addWidget(self.min_area_lcd)
		self.horizontalLayout_2.addLayout(self.verticalLayout_3)
		self.verticalLayout_4 = QtGui.QVBoxLayout()
		self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
		self.threshold1_edit = QtGui.QLineEdit(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.threshold1_edit.sizePolicy().hasHeightForWidth())
		self.threshold1_edit.setSizePolicy(sizePolicy)
		self.threshold1_edit.setObjectName(_fromUtf8("threshold1_edit"))
		self.verticalLayout_4.addWidget(self.threshold1_edit)
		self.threshold2_edit = QtGui.QLineEdit(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.threshold2_edit.sizePolicy().hasHeightForWidth())
		self.threshold2_edit.setSizePolicy(sizePolicy)
		self.threshold2_edit.setObjectName(_fromUtf8("threshold2_edit"))
		self.verticalLayout_4.addWidget(self.threshold2_edit)
		self.max_area_edit = QtGui.QLineEdit(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.max_area_edit.sizePolicy().hasHeightForWidth())
		self.max_area_edit.setSizePolicy(sizePolicy)
		self.max_area_edit.setObjectName(_fromUtf8("max_area_edit"))
		self.verticalLayout_4.addWidget(self.max_area_edit)
		self.min_area_edit = QtGui.QLineEdit(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.min_area_edit.sizePolicy().hasHeightForWidth())
		self.min_area_edit.setSizePolicy(sizePolicy)
		self.min_area_edit.setObjectName(_fromUtf8("min_area_edit"))
		self.verticalLayout_4.addWidget(self.min_area_edit)
		self.horizontalLayout_2.addLayout(self.verticalLayout_4)
		self.verticalLayout_5 = QtGui.QVBoxLayout()
		self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
		self.threshold1_slider = QtGui.QSlider(self.layoutWidget1)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.threshold1_slider.sizePolicy().hasHeightForWidth())
		self.threshold1_slider.setSizePolicy(sizePolicy)
		self.threshold1_slider.setMaximum(254)
		self.threshold1_slider.setOrientation(QtCore.Qt.Horizontal)
		self.threshold1_slider.setObjectName(_fromUtf8("threshold1_slider"))
		self.verticalLayout_5.addWidget(self.threshold1_slider)
		self.threshold2_slider = QtGui.QSlider(self.layoutWidget1)
		self.threshold2_slider.setMaximum(254)
		self.threshold2_slider.setOrientation(QtCore.Qt.Horizontal)
		self.threshold2_slider.setObjectName(_fromUtf8("threshold2_slider"))
		self.verticalLayout_5.addWidget(self.threshold2_slider)
		self.max_area_slider = QtGui.QSlider(self.layoutWidget1)
		self.max_area_slider.setMaximum(90000)
		self.max_area_slider.setOrientation(QtCore.Qt.Horizontal)
		self.max_area_slider.setObjectName(_fromUtf8("max_area_slider"))
		self.verticalLayout_5.addWidget(self.max_area_slider)
		self.min_area_slider = QtGui.QSlider(self.layoutWidget1)
		self.min_area_slider.setMaximum(90000)
		self.min_area_slider.setOrientation(QtCore.Qt.Horizontal)
		self.min_area_slider.setObjectName(_fromUtf8("min_area_slider"))
		self.verticalLayout_5.addWidget(self.min_area_slider)
		self.horizontalLayout_2.addLayout(self.verticalLayout_5)
		self.exec_button = QtGui.QPushButton(self.centralwidget)
		self.exec_button.setGeometry(QtCore.QRect(480, 20, 91, 61))
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.exec_button.sizePolicy().hasHeightForWidth())
		self.exec_button.setSizePolicy(sizePolicy)
		self.exec_button.setObjectName(_fromUtf8("exec_button"))
		Qt_CV_MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtGui.QMenuBar(Qt_CV_MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 24))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName(_fromUtf8("menuFile"))
		Qt_CV_MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(Qt_CV_MainWindow)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		Qt_CV_MainWindow.setStatusBar(self.statusbar)
		self.actionQuit = QtGui.QAction(Qt_CV_MainWindow)
		self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
		self.menuFile.addAction(self.actionQuit)
		self.menubar.addAction(self.menuFile.menuAction())

		self.retranslateUi(Qt_CV_MainWindow)
		QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), Qt_CV_MainWindow.close)
		QtCore.QObject.connect(self.threshold1_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.threshold1_lcd.display)
		QtCore.QObject.connect(self.threshold2_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.threshold2_lcd.display)
		QtCore.QObject.connect(self.max_area_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.max_area_lcd.display)
		QtCore.QObject.connect(self.threshold1_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.threshold2_lcd.display)
		QtCore.QObject.connect(self.threshold2_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.threshold2_lcd.display)
		QtCore.QObject.connect(self.max_area_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.max_area_lcd.display)
		QtCore.QMetaObject.connectSlotsByName(Qt_CV_MainWindow)

	def retranslateUi(self, Qt_CV_MainWindow):
		Qt_CV_MainWindow.setWindowTitle(_translate("Qt_CV_MainWindow", "Qt_OpenCV", None))
		self.file_button.setText(_translate("Qt_CV_MainWindow", "File", None))
		self.edge_con_ckbox.setText(_translate("Qt_CV_MainWindow", "Edge Contour eject", None))
		self.label.setText(_translate("Qt_CV_MainWindow", "High threshold", None))
		self.label_2.setText(_translate("Qt_CV_MainWindow", "Low threshold", None))
		self.label_3.setText(_translate("Qt_CV_MainWindow", "Max Area", None))
		self.label_4.setText(_translate("Qt_CV_MainWindow", "Min Area", None))
		self.exec_button.setText(_translate("Qt_CV_MainWindow", "Execute", None))
		self.menuFile.setTitle(_translate("Qt_CV_MainWindow", "File", None))
		self.actionQuit.setText(_translate("Qt_CV_MainWindow", "Quit", None))

from pyqtgraph import GraphicsLayoutWidget
