# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_Opencv.ui'
#
# Created: Sun Sep 21 11:56:39 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Qt_CV_MainWindow(object):
    def setupUi(self, Qt_CV_MainWindow):
        Qt_CV_MainWindow.setObjectName("Qt_CV_MainWindow")
        Qt_CV_MainWindow.resize(623, 684)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Qt_CV_MainWindow.sizePolicy().hasHeightForWidth())
        Qt_CV_MainWindow.setSizePolicy(sizePolicy)
        Qt_CV_MainWindow.setMouseTracking(True)
        Qt_CV_MainWindow.setAcceptDrops(False)
        self.centralwidget = QtGui.QWidget(Qt_CV_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pic_view = QtGui.QGraphicsView(self.centralwidget)
        self.pic_view.setGeometry(QtCore.QRect(10, 170, 591, 451))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic_view.sizePolicy().hasHeightForWidth())
        self.pic_view.setSizePolicy(sizePolicy)
        self.pic_view.setMouseTracking(True)
        self.pic_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pic_view.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pic_view.setTransformationAnchor(QtGui.QGraphicsView.AnchorUnderMouse)
        self.pic_view.setResizeAnchor(QtGui.QGraphicsView.AnchorUnderMouse)
        self.pic_view.setViewportUpdateMode(QtGui.QGraphicsView.SmartViewportUpdate)
        self.pic_view.setRubberBandSelectionMode(QtCore.Qt.ContainsItemBoundingRect)
        self.pic_view.setObjectName("pic_view")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 591, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_edit = QtGui.QLineEdit(self.layoutWidget)
        self.file_edit.setObjectName("file_edit")
        self.horizontalLayout.addWidget(self.file_edit)
        self.file_button = QtGui.QPushButton(self.layoutWidget)
        self.file_button.setObjectName("file_button")
        self.horizontalLayout.addWidget(self.file_button)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 10, 111, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.threshold1_lcd = QtGui.QLCDNumber(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold1_lcd.sizePolicy().hasHeightForWidth())
        self.threshold1_lcd.setSizePolicy(sizePolicy)
        self.threshold1_lcd.setObjectName("threshold1_lcd")
        self.horizontalLayout_4.addWidget(self.threshold1_lcd)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.threshold2_lcd = QtGui.QLCDNumber(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold2_lcd.sizePolicy().hasHeightForWidth())
        self.threshold2_lcd.setSizePolicy(sizePolicy)
        self.threshold2_lcd.setObjectName("threshold2_lcd")
        self.horizontalLayout_2.addWidget(self.threshold2_lcd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.size_lcd = QtGui.QLCDNumber(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.size_lcd.sizePolicy().hasHeightForWidth())
        self.size_lcd.setSizePolicy(sizePolicy)
        self.size_lcd.setObjectName("size_lcd")
        self.horizontalLayout_3.addWidget(self.size_lcd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(510, 20, 95, 65))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.exec_button = QtGui.QPushButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exec_button.sizePolicy().hasHeightForWidth())
        self.exec_button.setSizePolicy(sizePolicy)
        self.exec_button.setObjectName("exec_button")
        self.verticalLayout_2.addWidget(self.exec_button)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(330, 10, 156, 91))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.threshold1_slider = QtGui.QSlider(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold1_slider.sizePolicy().hasHeightForWidth())
        self.threshold1_slider.setSizePolicy(sizePolicy)
        self.threshold1_slider.setMaximum(254)
        self.threshold1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.threshold1_slider.setObjectName("threshold1_slider")
        self.verticalLayout_3.addWidget(self.threshold1_slider)
        self.threshold2_slider = QtGui.QSlider(self.layoutWidget3)
        self.threshold2_slider.setMaximum(254)
        self.threshold2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.threshold2_slider.setObjectName("threshold2_slider")
        self.verticalLayout_3.addWidget(self.threshold2_slider)
        self.size_slider = QtGui.QSlider(self.layoutWidget3)
        self.size_slider.setMaximum(90000)
        self.size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.size_slider.setObjectName("size_slider")
        self.verticalLayout_3.addWidget(self.size_slider)
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(230, 10, 156, 91))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.threshold1_edit = QtGui.QLineEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold1_edit.sizePolicy().hasHeightForWidth())
        self.threshold1_edit.setSizePolicy(sizePolicy)
        self.threshold1_edit.setObjectName("threshold1_edit")
        self.verticalLayout_4.addWidget(self.threshold1_edit)
        self.threshold2_edit = QtGui.QLineEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold2_edit.sizePolicy().hasHeightForWidth())
        self.threshold2_edit.setSizePolicy(sizePolicy)
        self.threshold2_edit.setObjectName("threshold2_edit")
        self.verticalLayout_4.addWidget(self.threshold2_edit)
        self.size_edit = QtGui.QLineEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.size_edit.sizePolicy().hasHeightForWidth())
        self.size_edit.setSizePolicy(sizePolicy)
        self.size_edit.setObjectName("size_edit")
        self.verticalLayout_4.addWidget(self.size_edit)
        self.layoutWidget5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 10, 101, 91))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtGui.QLabel(self.layoutWidget5)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget5)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        Qt_CV_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Qt_CV_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Qt_CV_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Qt_CV_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Qt_CV_MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(Qt_CV_MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Qt_CV_MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), Qt_CV_MainWindow.close)
        QtCore.QObject.connect(self.threshold1_slider, QtCore.SIGNAL("valueChanged(int)"), self.threshold1_lcd.display)
        QtCore.QObject.connect(self.threshold2_slider, QtCore.SIGNAL("valueChanged(int)"), self.threshold2_lcd.display)
        QtCore.QObject.connect(self.size_slider, QtCore.SIGNAL("valueChanged(int)"), self.size_lcd.display)
        QtCore.QObject.connect(self.threshold1_edit, QtCore.SIGNAL("textChanged(QString)"), self.threshold2_lcd.display)
        QtCore.QObject.connect(self.threshold2_edit, QtCore.SIGNAL("textChanged(QString)"), self.threshold2_lcd.display)
        QtCore.QObject.connect(self.size_edit, QtCore.SIGNAL("textChanged(QString)"), self.size_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(Qt_CV_MainWindow)

    def retranslateUi(self, Qt_CV_MainWindow):
        Qt_CV_MainWindow.setWindowTitle(QtGui.QApplication.translate("Qt_CV_MainWindow", "Qt_OpenCV", None, QtGui.QApplication.UnicodeUTF8))
        self.file_button.setText(QtGui.QApplication.translate("Qt_CV_MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.exec_button.setText(QtGui.QApplication.translate("Qt_CV_MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Qt_CV_MainWindow", "High threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Qt_CV_MainWindow", "Low threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Qt_CV_MainWindow", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Qt_CV_MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Qt_CV_MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

